### ISSUE TITLE
App Crash?

### ISSUE THREAD

**Issue by youhide** [MagicTheGathering/mtg-api#17]
Sometimes i get this:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by adback03** [comment]
The API has been receiving a much larger number of requests recently. I may have to implement stricter rate limits to help reduce the number of crashes. The other option is to increase server resources, but since this service is free, I'm not really looking towards investing more of my own cash at the moment.

I'll try to dig around more and see what else I can do.

**Comment by youhide** [comment]
how about scaling?

**Comment by adback03** [comment]
Yeah, but like I said, scaling isn't free :wink:. There are a few things I can try first, and if they don't work, I'll have to look into other options.
